
# server:
#   port: 8082
spring:
  # redis:
  #   host: 210.109.62.83
  #   port: 6379
  writedb:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://survey.jeonggyu-namespace.svc.cluster.local/survey?usessl=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root

  readdb:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://mysql-read-service.jeonggyu-namespace.svc.cluster.local/integration?usessl=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show-sql: true
        generate-ddl: true
