# server:
#   port: 8083

spring:
  writedb:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://user.jeonggyu-namespace.svc.cluster.local/user?usessl=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    hikari:
      maximum-pool-size: 10
  readdb:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://mysql-read-service.jeonggyu-namespace.svc.cluster.local/integration?usessl=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show-sql: true
        generate-ddl: true

  OAuth2:
      google:
        url: https://accounts.google.com/o/oauth2/v2/auth
        client-id:
        client-secret:
        callback-url: http://www.commfy.shop/auth/google/login/callback
        scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile

      kakao:
        client-id: 82dd132f5cde72bb709217456528f8b3
        authorization-uri: https://kauth.kakao.com/oauth/authorize
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me
        user-name-attribute: id
  profiles:
    include: oauth2

