services:
  survey:
    image: rnjsxorl3075/survey
    container_name: survey
    ports:
      - 8082:8082
  post:
    image: rnjsxorl3075/post
    container_name: post
    ports:
      - 8081:8081
  surveymanage:
    image: rnjsxorl3075/surveymanage
    container_name: surveymanage
    ports:
      - 8083:8083
  respondent:
    image: rnjsxorl3075/respondent
    container_name: respondent
    ports:
      - 8084:8084
  user:
    image: rnjsxorl3075/user
    container_name: user
    ports:
      - 8080:8080
 