server:
  port: 8080

spring:
  writedb:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://user-0.user.jeonggyu-namespace.svc.cluster.local/member?usessl=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root

  readdb:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://mysql-1.mysql-read-service.jeonggyu-namespace.svc.cluster.local/integration?usessl=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show-sql: true
        generate-ddl: true

  profiles:
    include: oauth2

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace