server:
  port: 8081

spring:
  # redis:
  #   host: 210.109.62.83
  #   port: 6379
  writedb:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://mysql-post-service/post?usessl=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 12345
    hikari:
      maximum-pool-size: 10
  readdb:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://mysql-read-service/comfy?usessl=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 12345
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show-sql: true
        generate-ddl: true

